name: Doc classification ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Use Node.js version 16
        uses: action/setuo-node@v2
        with:
          node-version: '16'
      - run: npm install
      